---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
      - PLEX_CLAIM=claimcode
    volumes:
      - /media/TV:/tv
      - /media/Movies:/movies
    restart: unless-stopped
