grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: unless-stopped
  privileged: true
  user: '1001'
  ports:
    - 192.168.1.224:3000:3000
  volumes:
    - /home/rsletten/data/grafana:/var/lib/grafana
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=mypassword
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SERVER_DOMAIN=rsletten.com
    - GF_SMTP_ENABLED=true
    - GF_SMTP_HOST=smtp.gmail.com:587
    - GF_SMTP_USER=rsletten@gmail.com
    - GF_SMTP_PASSWORD=mypassword
    - GF_SMTP_FROM_ADDRESS=rsletten@gmail.com
