---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/rsletten/data/radarr:/config
      - /mnt/8t/Movies:/movies1
      - /mnt/3t/Movies:/movies2
    ports:
      - 192.168.1.222:7878:7878
    restart: unless-stopped
