version: '2'
services:

  web:
    image: ansible/awx_web:10.0.0
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - 80:8052
    hostname: awxweb
    user: root
    volumes:
      - "/home/rsletten/data/awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/home/rsletten/data/awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/home/rsletten/data/awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/home/rsletten/data/awx/awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/home/rsletten/data/awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx_task:10.0.0
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "/home/rsletten/data/awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/home/rsletten/data/awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/home/rsletten/data/awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/home/rsletten/data/awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    container_name: awx_rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "awxpass"
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      http_proxy:
      https_proxy:
      no_proxy:

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  postgres:
    image: postgres:10
    container_name: awx_postgres
    volumes:
      - /home/rsletten/data/awx/pgdata/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy:
      https_proxy:
      no_proxy:
