---
version: "2"

services:
  tftpd:
    image: wastrachan/tftpd
    container_name: tftpd
    environment:
      - PUID:1000
      - PGID:1000
    volumes:
      - /home/rsletten/data/tftpboot:/data
      - /dev/log:/dev/log
    ports:
      - 192.168.1.226:69:69/udp
